sudo: false
language: python
cache: pip
python:
  - "3.4"
install:
  - pip install -U pip setuptools
  - pip install codecov
  - pip install shuup
  - pip install -r requirements-test.txt
script:
  - flake8 shuup_stripe/
  - isort --check-only
  - py.test -ra -vvv --nomigrations shuup_stripe_tests --cov shuup_stripe
after_success:
  - codecov
