sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
install:
  - pip install -U pip setuptools
  - pip install codecov
  - pip install shuup
  - pip install -r requirements-test.txt
script:
  - py.test -ra -vvv --nomigrations tests --cov
after_success: codecov
